package com.pq.tracs.model.vo;

import com.pq.tracs.model.eo.PrmOpportunityStatusImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 08 09:45:47 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrmOpportunityStatusViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getId();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        PrmOpportunityId {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getPrmOpportunityId();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setPrmOpportunityId((Number)value);
            }
        }
        ,
        StatusCode {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getStatusCode();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setStatusCode((String)value);
            }
        }
        ,
        StatusDate {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getStatusDate();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setStatusDate((Date)value);
            }
        }
        ,
        StatusNote {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getStatusNote();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setStatusNote((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        OpportunityStatusLookup {
            public Object get(PrmOpportunityStatusViewRowImpl obj) {
                return obj.getOpportunityStatusLookup();
            }

            public void put(PrmOpportunityStatusViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PrmOpportunityStatusViewRowImpl object);

        public abstract void put(PrmOpportunityStatusViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int PRMOPPORTUNITYID = AttributesEnum.PrmOpportunityId.index();
    public static final int STATUSCODE = AttributesEnum.StatusCode.index();
    public static final int STATUSDATE = AttributesEnum.StatusDate.index();
    public static final int STATUSNOTE = AttributesEnum.StatusNote.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int OPPORTUNITYSTATUSLOOKUP = AttributesEnum.OpportunityStatusLookup.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrmOpportunityStatusViewRowImpl() {
    }

    /**
     * Gets PrmOpportunityStatus entity object.
     * @return the PrmOpportunityStatus
     */
    public PrmOpportunityStatusImpl getPrmOpportunityStatus() {
        return (PrmOpportunityStatusImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for PRM_OPPORTUNITY_ID using the alias name PrmOpportunityId.
     * @return the PRM_OPPORTUNITY_ID
     */
    public Number getPrmOpportunityId() {
        return (Number) getAttributeInternal(PRMOPPORTUNITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRM_OPPORTUNITY_ID using the alias name PrmOpportunityId.
     * @param value value to set the PRM_OPPORTUNITY_ID
     */
    public void setPrmOpportunityId(Number value) {
        setAttributeInternal(PRMOPPORTUNITYID, value);
    }

    /**
     * Gets the attribute value for STATUS_CODE using the alias name StatusCode.
     * @return the STATUS_CODE
     */
    public String getStatusCode() {
        return (String) getAttributeInternal(STATUSCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_CODE using the alias name StatusCode.
     * @param value value to set the STATUS_CODE
     */
    public void setStatusCode(String value) {
        setAttributeInternal(STATUSCODE, value);
    }

    /**
     * Gets the attribute value for STATUS_DATE using the alias name StatusDate.
     * @return the STATUS_DATE
     */
    public Date getStatusDate() {
        return (Date) getAttributeInternal(STATUSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_DATE using the alias name StatusDate.
     * @param value value to set the STATUS_DATE
     */
    public void setStatusDate(Date value) {
        setAttributeInternal(STATUSDATE, value);
    }

    /**
     * Gets the attribute value for STATUS_NOTE using the alias name StatusNote.
     * @return the STATUS_NOTE
     */
    public String getStatusNote() {
        return (String) getAttributeInternal(STATUSNOTE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_NOTE using the alias name StatusNote.
     * @param value value to set the STATUS_NOTE
     */
    public void setStatusNote(String value) {
        setAttributeInternal(STATUSNOTE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OpportunityStatusLookup.
     */
    public RowSet getOpportunityStatusLookup() {
        return (RowSet)getAttributeInternal(OPPORTUNITYSTATUSLOOKUP);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
