package com.pq.tracs.model.vo;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 30 13:04:06 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NTCPublisherViewImpl extends PRMView {
    /**
     * This is the default constructor (do not remove).
     */
    public NTCPublisherViewImpl() {
    }
}
