package com.pq.tracs.model.vo;

import com.pq.tracs.model.eo.TraxActivityImpl;
import com.pq.tracs.model.eo.PrmBaseEntity;
import com.pq.tracs.model.eo.TraxActivityUserImpl;
import com.pq.tracs.model.eo.TraxRightsChangeImpl;

import com.pq.tracs.model.eo.TraxTitleChangeImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.RowCreateException;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 09 15:18:09 EDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NTCRightViewRowImpl extends ViewRowImpl {
    //         @Override
             protected void create(AttributeList attributeList) {
                 super.create(attributeList);

                 this.setType("NTC-B");
                 // The view row will already have created "blank" entity instances
                 TraxActivityImpl newActivity = this.getTraxActivity();
                 TraxActivityUserImpl newActivityUser = this.getTraxActivityUser();
                 TraxRightsChangeImpl NewRightsChange = this.getTraxRightsChange();
                 try {
                     // Let "blank" entity instance do programmatic defaulting
                     newActivity.create(attributeList);

                     NewRightsChange.create(newActivity);
                                NewRightsChange.setActivityId(newActivity.getId());
                     // create the activity user row and set the user type to Owner
                     newActivityUser.create(newActivity);
                     newActivityUser.setActivityId(newActivity.getId());
                     newActivityUser.setUserType("Owner");
                    newActivityUser.setAddDate(new Date(Date.getCurrentDate()));
                     this.setOwner(newActivityUser.getUserDisplayName());

                 } catch (JboException ex) {
                   newActivity.revert();
                     newActivityUser.revert();
                     NewRightsChange.revert();
                     throw ex;
                 } catch (Exception otherEx) {
                     newActivity.revert();
                     newActivityUser.revert();
                     NewRightsChange.revert();
                                throw new RowCreateException(true, /* EO Row? */"NTC Rights",
                                        /* EO Name */otherEx); /* Details */
                 }
             }


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getId();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        SubType {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getSubType();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setSubType((String)value);
            }
        }
        ,
        NtcNumber {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getNtcNumber();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setNtcNumber((Number)value);
            }
        }
        ,
        NtcPriority {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getNtcPriority();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setNtcPriority((String)value);
            }
        }
        ,
        Description {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getDescription();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Notes {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getNotes();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setNotes((String)value);
            }
        }
        ,
        EmailText {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getEmailText();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setEmailText((ClobDomain)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        Id1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getId1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setId1((Number)value);
            }
        }
        ,
        ActivityId {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getActivityId();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setActivityId((Number)value);
            }
        }
        ,
        FormatsInvolved {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getFormatsInvolved();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setFormatsInvolved((String)value);
            }
        }
        ,
        ProductTypesInvolved {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getProductTypesInvolved();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setProductTypesInvolved((String)value);
            }
        }
        ,
        ProductPartnersAffected {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getProductPartnersAffected();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setProductPartnersAffected((String)value);
            }
        }
        ,
        RemovalIs {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getRemovalIs();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setRemovalIs((String)value);
            }
        }
        ,
        BackfileProductPartners {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getBackfileProductPartners();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setBackfileProductPartners((String)value);
            }
        }
        ,
        BackfileProductRemoval {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getBackfileProductRemoval();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setBackfileProductRemoval((String)value);
            }
        }
        ,
        RemoveFromContentPartners {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getRemoveFromContentPartners();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setRemoveFromContentPartners((String)value);
            }
        }
        ,
        VolYearContinuedFlag {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getVolYearContinuedFlag();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setVolYearContinuedFlag((String)value);
            }
        }
        ,
        AAndIContinuedFlag {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getAAndIContinuedFlag();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setAAndIContinuedFlag((String)value);
            }
        }
        ,
        Id2 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getId2();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setId2((Number)value);
            }
        }
        ,
        LastUpdatedDate1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getLastUpdatedDate1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setLastUpdatedDate1((Date)value);
            }
        }
        ,
        ActivityId1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getActivityId1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setActivityId1((Number)value);
            }
        }
        ,
        JhsUsersId {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getJhsUsersId();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setJhsUsersId((Number)value);
            }
        }
        ,
        UserType {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getUserType();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setUserType((String)value);
            }
        }
        ,
        Owner {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getOwner();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setOwner((String)value);
            }
        }
        ,
        Type {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getType();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setType((String)value);
            }
        }
        ,
        ActualStartDate {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getActualStartDate();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setActualStartDate((Date)value);
            }
        }
        ,
        CompletionDate {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getCompletionDate();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setCompletionDate((Date)value);
            }
        }
        ,
        ContactId {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getContactId();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setContactId((Number)value);
            }
        }
        ,
        ContentOwnerId {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getContentOwnerId();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setContentOwnerId((Number)value);
            }
        }
        ,
        ContractId {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getContractId();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setContractId((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        DueDate {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getDueDate();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setDueDate((Date)value);
            }
        }
        ,
        ExpectedStartDate {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getExpectedStartDate();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setExpectedStartDate((Date)value);
            }
        }
        ,
        HoursSpent {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getHoursSpent();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setHoursSpent((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        Priority {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getPriority();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setPriority((String)value);
            }
        }
        ,
        Status {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        TitleId {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getTitleId();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setTitleId((Number)value);
            }
        }
        ,
        AddDate {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getAddDate();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setAddDate((Date)value);
            }
        }
        ,
        CreatedBy1_1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getCreatedBy1_1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setCreatedBy1_1((String)value);
            }
        }
        ,
        CreatedDate1_1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getCreatedDate1_1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setCreatedDate1_1((Date)value);
            }
        }
        ,
        LastUpdatedBy1_1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getLastUpdatedBy1_1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy1_1((String)value);
            }
        }
        ,
        RemovedDate {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getRemovedDate();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setRemovedDate((Date)value);
            }
        }
        ,
        CreatedBy2_1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getCreatedBy2_1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setCreatedBy2_1((String)value);
            }
        }
        ,
        CreatedDate2_1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getCreatedDate2_1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setCreatedDate2_1((Date)value);
            }
        }
        ,
        LastBackfileDate {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getLastBackfileDate();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setLastBackfileDate((String)value);
            }
        }
        ,
        LastUpdatedBy2_1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getLastUpdatedBy2_1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy2_1((String)value);
            }
        }
        ,
        LastUpdatedDate2_1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getLastUpdatedDate2_1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setLastUpdatedDate2_1((Date)value);
            }
        }
        ,
        TraxActivityTitleView {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getTraxActivityTitleView();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TraxActivityAttachmentView {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getTraxActivityAttachmentView();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmLookupModule_NTCContentPartnerLookup1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getPrmLookupModule_NTCContentPartnerLookup1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmLookupModule_NTCFormatLookup1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getPrmLookupModule_NTCFormatLookup1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmLookupModule_NTCProductTypeLookup1 {
            public Object get(NTCRightViewRowImpl obj) {
                return obj.getPrmLookupModule_NTCProductTypeLookup1();
            }

            public void put(NTCRightViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(NTCRightViewRowImpl object);

        public abstract void put(NTCRightViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int SUBTYPE = AttributesEnum.SubType.index();
    public static final int NTCNUMBER = AttributesEnum.NtcNumber.index();
    public static final int NTCPRIORITY = AttributesEnum.NtcPriority.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int EMAILTEXT = AttributesEnum.EmailText.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ID1 = AttributesEnum.Id1.index();
    public static final int ACTIVITYID = AttributesEnum.ActivityId.index();
    public static final int FORMATSINVOLVED = AttributesEnum.FormatsInvolved.index();
    public static final int PRODUCTTYPESINVOLVED = AttributesEnum.ProductTypesInvolved.index();
    public static final int PRODUCTPARTNERSAFFECTED = AttributesEnum.ProductPartnersAffected.index();
    public static final int REMOVALIS = AttributesEnum.RemovalIs.index();
    public static final int BACKFILEPRODUCTPARTNERS = AttributesEnum.BackfileProductPartners.index();
    public static final int BACKFILEPRODUCTREMOVAL = AttributesEnum.BackfileProductRemoval.index();
    public static final int REMOVEFROMCONTENTPARTNERS = AttributesEnum.RemoveFromContentPartners.index();
    public static final int VOLYEARCONTINUEDFLAG = AttributesEnum.VolYearContinuedFlag.index();
    public static final int AANDICONTINUEDFLAG = AttributesEnum.AAndIContinuedFlag.index();
    public static final int ID2 = AttributesEnum.Id2.index();
    public static final int LASTUPDATEDDATE1 = AttributesEnum.LastUpdatedDate1.index();
    public static final int ACTIVITYID1 = AttributesEnum.ActivityId1.index();
    public static final int JHSUSERSID = AttributesEnum.JhsUsersId.index();
    public static final int USERTYPE = AttributesEnum.UserType.index();
    public static final int OWNER = AttributesEnum.Owner.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int ACTUALSTARTDATE = AttributesEnum.ActualStartDate.index();
    public static final int COMPLETIONDATE = AttributesEnum.CompletionDate.index();
    public static final int CONTACTID = AttributesEnum.ContactId.index();
    public static final int CONTENTOWNERID = AttributesEnum.ContentOwnerId.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int DUEDATE = AttributesEnum.DueDate.index();
    public static final int EXPECTEDSTARTDATE = AttributesEnum.ExpectedStartDate.index();
    public static final int HOURSSPENT = AttributesEnum.HoursSpent.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PRIORITY = AttributesEnum.Priority.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TITLEID = AttributesEnum.TitleId.index();
    public static final int ADDDATE = AttributesEnum.AddDate.index();
    public static final int CREATEDBY1_1 = AttributesEnum.CreatedBy1_1.index();
    public static final int CREATEDDATE1_1 = AttributesEnum.CreatedDate1_1.index();
    public static final int LASTUPDATEDBY1_1 = AttributesEnum.LastUpdatedBy1_1.index();
    public static final int REMOVEDDATE = AttributesEnum.RemovedDate.index();
    public static final int CREATEDBY2_1 = AttributesEnum.CreatedBy2_1.index();
    public static final int CREATEDDATE2_1 = AttributesEnum.CreatedDate2_1.index();
    public static final int LASTBACKFILEDATE = AttributesEnum.LastBackfileDate.index();
    public static final int LASTUPDATEDBY2_1 = AttributesEnum.LastUpdatedBy2_1.index();
    public static final int LASTUPDATEDDATE2_1 = AttributesEnum.LastUpdatedDate2_1.index();
    public static final int TRAXACTIVITYTITLEVIEW = AttributesEnum.TraxActivityTitleView.index();
    public static final int TRAXACTIVITYATTACHMENTVIEW = AttributesEnum.TraxActivityAttachmentView.index();
    public static final int PRMLOOKUPMODULE_NTCCONTENTPARTNERLOOKUP1 = AttributesEnum.PrmLookupModule_NTCContentPartnerLookup1.index();
    public static final int PRMLOOKUPMODULE_NTCFORMATLOOKUP1 = AttributesEnum.PrmLookupModule_NTCFormatLookup1.index();
    public static final int PRMLOOKUPMODULE_NTCPRODUCTTYPELOOKUP1 = AttributesEnum.PrmLookupModule_NTCProductTypeLookup1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NTCRightViewRowImpl() {
    }

    /**
     * Gets TraxActivity entity object.
     * @return the TraxActivity
     */
    public TraxActivityImpl getTraxActivity() {
        return (TraxActivityImpl)getEntity(0);
    }

    /**
     * Gets TraxActivityUser entity object.
     * @return the TraxActivityUser
     */
    public TraxActivityUserImpl getTraxActivityUser() {
        return (TraxActivityUserImpl)getEntity(1);
    }

    /**
     * Gets TraxRightsChange entity object.
     * @return the TraxRightsChange
     */
    public TraxRightsChangeImpl getTraxRightsChange() {
        return (TraxRightsChangeImpl)getEntity(2);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for SUB_TYPE using the alias name SubType.
     * @return the SUB_TYPE
     */
    public String getSubType() {
        return (String) getAttributeInternal(SUBTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_TYPE using the alias name SubType.
     * @param value value to set the SUB_TYPE
     */
    public void setSubType(String value) {
        setAttributeInternal(SUBTYPE, value);
    }

    /**
     * Gets the attribute value for NTC_NUMBER using the alias name NtcNumber.
     * @return the NTC_NUMBER
     */
    public Number getNtcNumber() {
        return (Number)getAttributeInternal(NTCNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for NTC_NUMBER using the alias name NtcNumber.
     * @param value value to set the NTC_NUMBER
     */
    public void setNtcNumber(Number value) {
        setAttributeInternal(NTCNUMBER, value);
    }

    /**
     * Gets the attribute value for NTC_PRIORITY using the alias name NtcPriority.
     * @return the NTC_PRIORITY
     */
    public String getNtcPriority() {
        return (String) getAttributeInternal(NTCPRIORITY);
    }

    /**
     * Sets <code>value</code> as attribute value for NTC_PRIORITY using the alias name NtcPriority.
     * @param value value to set the NTC_PRIORITY
     */
    public void setNtcPriority(String value) {
        setAttributeInternal(NTCPRIORITY, value);
    }


    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for NOTES using the alias name Notes.
     * @return the NOTES
     */
    public String getNotes() {
        return (String) getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTES using the alias name Notes.
     * @param value value to set the NOTES
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * Gets the attribute value for EMAIL_TEXT using the alias name EmailText.
     * @return the EMAIL_TEXT
     */
    public ClobDomain getEmailText() {
        return (ClobDomain)getAttributeInternal(EMAILTEXT);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL_TEXT using the alias name EmailText.
     * @param value value to set the EMAIL_TEXT
     */
    public void setEmailText(ClobDomain value) {
        setAttributeInternal(EMAILTEXT, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id1.
     * @return the ID
     */
    public Number getId1() {
        return (Number)getAttributeInternal(ID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id1.
     * @param value value to set the ID
     */
    public void setId1(Number value) {
        setAttributeInternal(ID1, value);
    }

    /**
     * Gets the attribute value for ACTIVITY_ID using the alias name ActivityId.
     * @return the ACTIVITY_ID
     */
    public Number getActivityId() {
        return (Number)getAttributeInternal(ACTIVITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVITY_ID using the alias name ActivityId.
     * @param value value to set the ACTIVITY_ID
     */
    public void setActivityId(Number value) {
        setAttributeInternal(ACTIVITYID, value);
    }

    /**
     * Gets the attribute value for FORMATS_INVOLVED using the alias name FormatsInvolved.
     * @return the FORMATS_INVOLVED
     */
    public String getFormatsInvolved() {
        return (String) getAttributeInternal(FORMATSINVOLVED);
    }

    /**
     * Sets <code>value</code> as attribute value for FORMATS_INVOLVED using the alias name FormatsInvolved.
     * @param value value to set the FORMATS_INVOLVED
     */
    public void setFormatsInvolved(String value) {
        setAttributeInternal(FORMATSINVOLVED, value);
    }

    /**
     * Gets the attribute value for PRODUCT_TYPES_INVOLVED using the alias name ProductTypesInvolved.
     * @return the PRODUCT_TYPES_INVOLVED
     */
    public String getProductTypesInvolved() {
        return (String) getAttributeInternal(PRODUCTTYPESINVOLVED);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_TYPES_INVOLVED using the alias name ProductTypesInvolved.
     * @param value value to set the PRODUCT_TYPES_INVOLVED
     */
    public void setProductTypesInvolved(String value) {
        setAttributeInternal(PRODUCTTYPESINVOLVED, value);
    }

    /**
     * Gets the attribute value for PRODUCT_PARTNERS_AFFECTED using the alias name ProductPartnersAffected.
     * @return the PRODUCT_PARTNERS_AFFECTED
     */
    public String getProductPartnersAffected() {
        return (String) getAttributeInternal(PRODUCTPARTNERSAFFECTED);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_PARTNERS_AFFECTED using the alias name ProductPartnersAffected.
     * @param value value to set the PRODUCT_PARTNERS_AFFECTED
     */
    public void setProductPartnersAffected(String value) {
        setAttributeInternal(PRODUCTPARTNERSAFFECTED, value);
    }

    /**
     * Gets the attribute value for REMOVAL_IS using the alias name RemovalIs.
     * @return the REMOVAL_IS
     */
    public String getRemovalIs() {
        return (String) getAttributeInternal(REMOVALIS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMOVAL_IS using the alias name RemovalIs.
     * @param value value to set the REMOVAL_IS
     */
    public void setRemovalIs(String value) {
        setAttributeInternal(REMOVALIS, value);
    }

    /**
     * Gets the attribute value for BACKFILE_PRODUCT_PARTNERS using the alias name BackfileProductPartners.
     * @return the BACKFILE_PRODUCT_PARTNERS
     */
    public String getBackfileProductPartners() {
        return (String) getAttributeInternal(BACKFILEPRODUCTPARTNERS);
    }

    /**
     * Sets <code>value</code> as attribute value for BACKFILE_PRODUCT_PARTNERS using the alias name BackfileProductPartners.
     * @param value value to set the BACKFILE_PRODUCT_PARTNERS
     */
    public void setBackfileProductPartners(String value) {
        setAttributeInternal(BACKFILEPRODUCTPARTNERS, value);
    }

    /**
     * Gets the attribute value for BACKFILE_PRODUCT_REMOVAL using the alias name BackfileProductRemoval.
     * @return the BACKFILE_PRODUCT_REMOVAL
     */
    public String getBackfileProductRemoval() {
        return (String) getAttributeInternal(BACKFILEPRODUCTREMOVAL);
    }

    /**
     * Sets <code>value</code> as attribute value for BACKFILE_PRODUCT_REMOVAL using the alias name BackfileProductRemoval.
     * @param value value to set the BACKFILE_PRODUCT_REMOVAL
     */
    public void setBackfileProductRemoval(String value) {
        setAttributeInternal(BACKFILEPRODUCTREMOVAL, value);
    }

    /**
     * Gets the attribute value for REMOVE_FROM_CONTENT_PARTNERS using the alias name RemoveFromContentPartners.
     * @return the REMOVE_FROM_CONTENT_PARTNERS
     */
    public String getRemoveFromContentPartners() {
        return (String) getAttributeInternal(REMOVEFROMCONTENTPARTNERS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMOVE_FROM_CONTENT_PARTNERS using the alias name RemoveFromContentPartners.
     * @param value value to set the REMOVE_FROM_CONTENT_PARTNERS
     */
    public void setRemoveFromContentPartners(String value) {
        setAttributeInternal(REMOVEFROMCONTENTPARTNERS, value);
    }

    /**
     * Gets the attribute value for VOL_YEAR_CONTINUED_FLAG using the alias name VolYearContinuedFlag.
     * @return the VOL_YEAR_CONTINUED_FLAG
     */
    public String getVolYearContinuedFlag() {
        return (String) getAttributeInternal(VOLYEARCONTINUEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for VOL_YEAR_CONTINUED_FLAG using the alias name VolYearContinuedFlag.
     * @param value value to set the VOL_YEAR_CONTINUED_FLAG
     */
    public void setVolYearContinuedFlag(String value) {
        setAttributeInternal(VOLYEARCONTINUEDFLAG, value);
    }

    /**
     * Gets the attribute value for A_AND_I_CONTINUED_FLAG using the alias name AAndIContinuedFlag.
     * @return the A_AND_I_CONTINUED_FLAG
     */
    public String getAAndIContinuedFlag() {
        return (String) getAttributeInternal(AANDICONTINUEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for A_AND_I_CONTINUED_FLAG using the alias name AAndIContinuedFlag.
     * @param value value to set the A_AND_I_CONTINUED_FLAG
     */
    public void setAAndIContinuedFlag(String value) {
        setAttributeInternal(AANDICONTINUEDFLAG, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id2.
     * @return the ID
     */
    public Number getId2() {
        return (Number)getAttributeInternal(ID2);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id2.
     * @param value value to set the ID
     */
    public void setId2(Number value) {
        setAttributeInternal(ID2, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate1.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate1() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate1.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate1(Date value) {
        setAttributeInternal(LASTUPDATEDDATE1, value);
    }

    /**
     * Gets the attribute value for ACTIVITY_ID using the alias name ActivityId1.
     * @return the ACTIVITY_ID
     */
    public Number getActivityId1() {
        return (Number)getAttributeInternal(ACTIVITYID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVITY_ID using the alias name ActivityId1.
     * @param value value to set the ACTIVITY_ID
     */
    public void setActivityId1(Number value) {
        setAttributeInternal(ACTIVITYID1, value);
    }

    /**
     * Gets the attribute value for JHS_USERS_ID using the alias name JhsUsersId.
     * @return the JHS_USERS_ID
     */
    public Number getJhsUsersId() {
        return (Number)getAttributeInternal(JHSUSERSID);
    }

    /**
     * Sets <code>value</code> as attribute value for JHS_USERS_ID using the alias name JhsUsersId.
     * @param value value to set the JHS_USERS_ID
     */
    public void setJhsUsersId(Number value) {
        setAttributeInternal(JHSUSERSID, value);
    }

    /**
     * Gets the attribute value for USER_TYPE using the alias name UserType.
     * @return the USER_TYPE
     */
    public String getUserType() {
        return (String) getAttributeInternal(USERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_TYPE using the alias name UserType.
     * @param value value to set the USER_TYPE
     */
    public void setUserType(String value) {
        setAttributeInternal(USERTYPE, value);
    }

    /**
     * Gets the attribute value for OWNER using the alias name Owner.
     * @return the OWNER
     */
    public String getOwner() {
        return (String) getAttributeInternal(OWNER);
    }

    /**
     * Sets <code>value</code> as attribute value for OWNER using the alias name Owner.
     * @param value value to set the OWNER
     */
    public void setOwner(String value) {
        setAttributeInternal(OWNER, value);
    }

    /**
     * Gets the attribute value for TYPE using the alias name Type.
     * @return the TYPE
     */
    public String getType() {
        return (String) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE using the alias name Type.
     * @param value value to set the TYPE
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActualStartDate.
     * @return the ActualStartDate
     */
    public Date getActualStartDate() {
        return (Date)getAttributeInternal(ACTUALSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActualStartDate.
     * @param value value to set the  ActualStartDate
     */
    public void setActualStartDate(Date value) {
        setAttributeInternal(ACTUALSTARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompletionDate.
     * @return the CompletionDate
     */
    public Date getCompletionDate() {
        return (Date)getAttributeInternal(COMPLETIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompletionDate.
     * @param value value to set the  CompletionDate
     */
    public void setCompletionDate(Date value) {
        setAttributeInternal(COMPLETIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContactId.
     * @return the ContactId
     */
    public Number getContactId() {
        return (Number)getAttributeInternal(CONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContactId.
     * @param value value to set the  ContactId
     */
    public void setContactId(Number value) {
        setAttributeInternal(CONTACTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContentOwnerId.
     * @return the ContentOwnerId
     */
    public Number getContentOwnerId() {
        return (Number)getAttributeInternal(CONTENTOWNERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContentOwnerId.
     * @param value value to set the  ContentOwnerId
     */
    public void setContentOwnerId(Number value) {
        setAttributeInternal(CONTENTOWNERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContractId.
     * @return the ContractId
     */
    public Number getContractId() {
        return (Number)getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContractId.
     * @param value value to set the  ContractId
     */
    public void setContractId(Number value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedDate.
     * @param value value to set the  CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DueDate.
     * @return the DueDate
     */
    public Date getDueDate() {
        return (Date)getAttributeInternal(DUEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DueDate.
     * @param value value to set the  DueDate
     */
    public void setDueDate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExpectedStartDate.
     * @return the ExpectedStartDate
     */
    public Date getExpectedStartDate() {
        return (Date)getAttributeInternal(EXPECTEDSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExpectedStartDate.
     * @param value value to set the  ExpectedStartDate
     */
    public void setExpectedStartDate(Date value) {
        setAttributeInternal(EXPECTEDSTARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HoursSpent.
     * @return the HoursSpent
     */
    public Number getHoursSpent() {
        return (Number)getAttributeInternal(HOURSSPENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HoursSpent.
     * @param value value to set the  HoursSpent
     */
    public void setHoursSpent(Number value) {
        setAttributeInternal(HOURSSPENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy.
     * @param value value to set the  LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Priority.
     * @return the Priority
     */
    public String getPriority() {
        return (String) getAttributeInternal(PRIORITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Priority.
     * @param value value to set the  Priority
     */
    public void setPriority(String value) {
        setAttributeInternal(PRIORITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TitleId.
     * @return the TitleId
     */
    public Number getTitleId() {
        return (Number)getAttributeInternal(TITLEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TitleId.
     * @param value value to set the  TitleId
     */
    public void setTitleId(Number value) {
        setAttributeInternal(TITLEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AddDate.
     * @return the AddDate
     */
    public Date getAddDate() {
        return (Date)getAttributeInternal(ADDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AddDate.
     * @param value value to set the  AddDate
     */
    public void setAddDate(Date value) {
        setAttributeInternal(ADDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy1_1.
     * @return the CreatedBy1_1
     */
    public String getCreatedBy1_1() {
        return (String) getAttributeInternal(CREATEDBY1_1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy1_1.
     * @param value value to set the  CreatedBy1_1
     */
    public void setCreatedBy1_1(String value) {
        setAttributeInternal(CREATEDBY1_1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedDate1_1.
     * @return the CreatedDate1_1
     */
    public Date getCreatedDate1_1() {
        return (Date)getAttributeInternal(CREATEDDATE1_1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedDate1_1.
     * @param value value to set the  CreatedDate1_1
     */
    public void setCreatedDate1_1(Date value) {
        setAttributeInternal(CREATEDDATE1_1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy1_1.
     * @return the LastUpdatedBy1_1
     */
    public String getLastUpdatedBy1_1() {
        return (String) getAttributeInternal(LASTUPDATEDBY1_1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy1_1.
     * @param value value to set the  LastUpdatedBy1_1
     */
    public void setLastUpdatedBy1_1(String value) {
        setAttributeInternal(LASTUPDATEDBY1_1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemovedDate.
     * @return the RemovedDate
     */
    public Date getRemovedDate() {
        return (Date)getAttributeInternal(REMOVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemovedDate.
     * @param value value to set the  RemovedDate
     */
    public void setRemovedDate(Date value) {
        setAttributeInternal(REMOVEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy2_1.
     * @return the CreatedBy2_1
     */
    public String getCreatedBy2_1() {
        return (String) getAttributeInternal(CREATEDBY2_1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy2_1.
     * @param value value to set the  CreatedBy2_1
     */
    public void setCreatedBy2_1(String value) {
        setAttributeInternal(CREATEDBY2_1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedDate2_1.
     * @return the CreatedDate2_1
     */
    public Date getCreatedDate2_1() {
        return (Date)getAttributeInternal(CREATEDDATE2_1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedDate2_1.
     * @param value value to set the  CreatedDate2_1
     */
    public void setCreatedDate2_1(Date value) {
        setAttributeInternal(CREATEDDATE2_1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastBackfileDate.
     * @return the LastBackfileDate
     */
    public String getLastBackfileDate() {
        return (String) getAttributeInternal(LASTBACKFILEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastBackfileDate.
     * @param value value to set the  LastBackfileDate
     */
    public void setLastBackfileDate(String value) {
        setAttributeInternal(LASTBACKFILEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy2_1.
     * @return the LastUpdatedBy2_1
     */
    public String getLastUpdatedBy2_1() {
        return (String) getAttributeInternal(LASTUPDATEDBY2_1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy2_1.
     * @param value value to set the  LastUpdatedBy2_1
     */
    public void setLastUpdatedBy2_1(String value) {
        setAttributeInternal(LASTUPDATEDBY2_1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedDate2_1.
     * @return the LastUpdatedDate2_1
     */
    public Date getLastUpdatedDate2_1() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE2_1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedDate2_1.
     * @param value value to set the  LastUpdatedDate2_1
     */
    public void setLastUpdatedDate2_1(Date value) {
        setAttributeInternal(LASTUPDATEDDATE2_1, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TraxActivityAttachmentView.
     */
    public RowIterator getTraxActivityAttachmentView() {
        return (RowIterator)getAttributeInternal(TRAXACTIVITYATTACHMENTVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TraxActivityTitleView.
     */
    public RowIterator getTraxActivityTitleView() {
        return (RowIterator)getAttributeInternal(TRAXACTIVITYTITLEVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PrmLookupModule_NTCContentPartnerLookup1.
     */
    public RowSet getPrmLookupModule_NTCContentPartnerLookup1() {
        return (RowSet)getAttributeInternal(PRMLOOKUPMODULE_NTCCONTENTPARTNERLOOKUP1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PrmLookupModule_NTCFormatLookup1.
     */
    public RowSet getPrmLookupModule_NTCFormatLookup1() {
        return (RowSet)getAttributeInternal(PRMLOOKUPMODULE_NTCFORMATLOOKUP1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PrmLookupModule_NTCProductTypeLookup1.
     */
    public RowSet getPrmLookupModule_NTCProductTypeLookup1() {
        return (RowSet)getAttributeInternal(PRMLOOKUPMODULE_NTCPRODUCTTYPELOOKUP1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
