package com.pq.tracs.model.vo;

import com.pq.tracs.model.eo.PrmTargetGroupImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 09 20:35:02 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrmTargetGroupViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getId();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        GroupNo {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getGroupNo();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setGroupNo((String)value);
            }
        }
        ,
        GroupName {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getGroupName();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setGroupName((String)value);
            }
        }
        ,
        ProductCount {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getProductCount();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setProductCount((Integer)value);
            }
        }
        ,
        TitleCount {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getTitleCount();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setTitleCount((Integer)value);
            }
        }
        ,
        GroupType {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getGroupType();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setGroupType((String)value);
            }
        }
        ,
        ImportFileId {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getImportFileId();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setImportFileId((Number)value);
            }
        }
        ,
        FileName {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getFileName();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setFileName((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        PrmTargetGroupTitleView {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getPrmTargetGroupTitleView();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmTargetGroupProductView {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getPrmTargetGroupProductView();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmTargetedProductTitleView {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getPrmTargetedProductTitleView();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TargetGroupTypeLookup {
            public Object get(PrmTargetGroupViewRowImpl obj) {
                return obj.getTargetGroupTypeLookup();
            }

            public void put(PrmTargetGroupViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PrmTargetGroupViewRowImpl object);

        public abstract void put(PrmTargetGroupViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int GROUPNO = AttributesEnum.GroupNo.index();
    public static final int GROUPNAME = AttributesEnum.GroupName.index();
    public static final int PRODUCTCOUNT = AttributesEnum.ProductCount.index();
    public static final int TITLECOUNT = AttributesEnum.TitleCount.index();
    public static final int GROUPTYPE = AttributesEnum.GroupType.index();
    public static final int IMPORTFILEID = AttributesEnum.ImportFileId.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int PRMTARGETGROUPTITLEVIEW = AttributesEnum.PrmTargetGroupTitleView.index();
    public static final int PRMTARGETGROUPPRODUCTVIEW = AttributesEnum.PrmTargetGroupProductView.index();
    public static final int PRMTARGETEDPRODUCTTITLEVIEW = AttributesEnum.PrmTargetedProductTitleView.index();
    public static final int TARGETGROUPTYPELOOKUP = AttributesEnum.TargetGroupTypeLookup.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrmTargetGroupViewRowImpl() {
    }

    /**
     * Gets PrmTargetGroup entity object.
     * @return the PrmTargetGroup
     */
    public PrmTargetGroupImpl getPrmTargetGroup() {
        return (PrmTargetGroupImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for GROUP_NO using the alias name GroupNo.
     * @return the GROUP_NO
     */
    public String getGroupNo() {
        return (String) getAttributeInternal(GROUPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_NO using the alias name GroupNo.
     * @param value value to set the GROUP_NO
     */
    public void setGroupNo(String value) {
        setAttributeInternal(GROUPNO, value);
    }

    /**
     * Gets the attribute value for GROUP_NAME using the alias name GroupName.
     * @return the GROUP_NAME
     */
    public String getGroupName() {
        return (String) getAttributeInternal(GROUPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_NAME using the alias name GroupName.
     * @param value value to set the GROUP_NAME
     */
    public void setGroupName(String value) {
        setAttributeInternal(GROUPNAME, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductCount.
     * @return the ProductCount
     */
    public Integer getProductCount() {
        return (Integer) getAttributeInternal(PRODUCTCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductCount.
     * @param value value to set the  ProductCount
     */
    public void setProductCount(Integer value) {
        setAttributeInternal(PRODUCTCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TitleCount.
     * @return the TitleCount
     */
    public Integer getTitleCount() {
        return (Integer) getAttributeInternal(TITLECOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TitleCount.
     * @param value value to set the  TitleCount
     */
    public void setTitleCount(Integer value) {
        setAttributeInternal(TITLECOUNT, value);
    }

    /**
     * Gets the attribute value for GROUP_TYPE using the alias name GroupType.
     * @return the GROUP_TYPE
     */
    public String getGroupType() {
        return (String) getAttributeInternal(GROUPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_TYPE using the alias name GroupType.
     * @param value value to set the GROUP_TYPE
     */
    public void setGroupType(String value) {
        setAttributeInternal(GROUPTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ImportFileId.
     * @return the ImportFileId
     */
    public Number getImportFileId() {
        return (Number)getAttributeInternal(IMPORTFILEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ImportFileId.
     * @param value value to set the  ImportFileId
     */
    public void setImportFileId(Number value) {
        setAttributeInternal(IMPORTFILEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FileName.
     * @return the FileName
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FileName.
     * @param value value to set the  FileName
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PrmTargetGroupTitleView.
     */
    public RowIterator getPrmTargetGroupTitleView() {
        return (RowIterator)getAttributeInternal(PRMTARGETGROUPTITLEVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PrmTargetGroupProductView.
     */
    public RowIterator getPrmTargetGroupProductView() {
        return (RowIterator)getAttributeInternal(PRMTARGETGROUPPRODUCTVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PrmTargetedProductTitleView.
     */
    public RowIterator getPrmTargetedProductTitleView() {
        return (RowIterator)getAttributeInternal(PRMTARGETEDPRODUCTTITLEVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TargetGroupTypeLookup.
     */
    public RowSet getTargetGroupTypeLookup() {
        return (RowSet)getAttributeInternal(TARGETGROUPTYPELOOKUP);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
