package com.pq.tracs.model.vo;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 18 08:33:43 EST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrmAccountProductDisciplineViewImpl extends PRMView {
    /**
     * This is the default constructor (do not remove).
     */
    public PrmAccountProductDisciplineViewImpl() {
    }
}
