package com.pq.tracs.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 30 10:40:19 EST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrmOpportunityAgreementDataImpl extends PrmBaseEntity {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getId();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        PrmOpportunityId {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getPrmOpportunityId();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setPrmOpportunityId((Number)value);
            }
        }
        ,
        ContractId {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getContractId();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setContractId((Number)value);
            }
        }
        ,
        TemplateId {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getTemplateId();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setTemplateId((Number)value);
            }
        }
        ,
        Notes {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getNotes();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setNotes((String)value);
            }
        }
        ,
        Form {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getForm();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setForm((String)value);
            }
        }
        ,
        Status {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getStatus();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Type {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getType();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setType((String)value);
            }
        }
        ,
        Division {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getDivision();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setDivision((String)value);
            }
        }
        ,
        EffectiveDate {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getEffectiveDate();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setEffectiveDate((Date)value);
            }
        }
        ,
        TermLength {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getTermLength();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setTermLength((String)value);
            }
        }
        ,
        CancellationNoticeTerm {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getCancellationNoticeTerm();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setCancellationNoticeTerm((Number)value);
            }
        }
        ,
        ExpirationDate {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getExpirationDate();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setExpirationDate((Date)value);
            }
        }
        ,
        AutoRenewTermMonths {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getAutoRenewTermMonths();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setAutoRenewTermMonths((Number)value);
            }
        }
        ,
        Signatory {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getSignatory();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setSignatory((String)value);
            }
        }
        ,
        ContractSignedDate {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getContractSignedDate();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setContractSignedDate((Date)value);
            }
        }
        ,
        RightsToBeRetained {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getRightsToBeRetained();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setRightsToBeRetained((String)value);
            }
        }
        ,
        Exclusivity {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getExclusivity();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setExclusivity((String)value);
            }
        }
        ,
        ContentMasterOwner {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getContentMasterOwner();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setContentMasterOwner((String)value);
            }
        }
        ,
        TechnicalContactId {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getTechnicalContactId();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setTechnicalContactId((Number)value);
            }
        }
        ,
        AgreementContactId {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getAgreementContactId();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setAgreementContactId((Number)value);
            }
        }
        ,
        QaContactId {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getQaContactId();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setQaContactId((Number)value);
            }
        }
        ,
        RoyaltyContactId {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getRoyaltyContactId();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setRoyaltyContactId((Number)value);
            }
        }
        ,
        Currency {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getCurrency();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        PaymentFrequency {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getPaymentFrequency();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setPaymentFrequency((String)value);
            }
        }
        ,
        InterimPaymentTermDays {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getInterimPaymentTermDays();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setInterimPaymentTermDays((Number)value);
            }
        }
        ,
        AnnualPaymentTermDays {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getAnnualPaymentTermDays();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setAnnualPaymentTermDays((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        AutoRenewal {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getAutoRenewal();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setAutoRenewal((String)value);
            }
        }
        ,
        AutoAdd {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getAutoAdd();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setAutoAdd((String)value);
            }
        }
        ,
        Assignment {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getAssignment();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setAssignment((String)value);
            }
        }
        ,
        RoyaltyBearing {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getRoyaltyBearing();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setRoyaltyBearing((String)value);
            }
        }
        ,
        Guarantee {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getGuarantee();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setGuarantee((String)value);
            }
        }
        ,
        FairTreatmentClause {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getFairTreatmentClause();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setFairTreatmentClause((String)value);
            }
        }
        ,
        IssueEditionCoverage {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getIssueEditionCoverage();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setIssueEditionCoverage((String)value);
            }
        }
        ,
        CompleteContentSet {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getCompleteContentSet();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setCompleteContentSet((String)value);
            }
        }
        ,
        WarrantyAndIndemnification {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getWarrantyAndIndemnification();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setWarrantyAndIndemnification((String)value);
            }
        }
        ,
        Governance {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getGovernance();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setGovernance((String)value);
            }
        }
        ,
        PrmOpportunity {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getPrmOpportunity();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setPrmOpportunity((PrmOpportunityImpl)value);
            }
        }
        ,
        PrmAgreemntDataAttachment {
            public Object get(PrmOpportunityAgreementDataImpl obj) {
                return obj.getPrmAgreemntDataAttachment();
            }

            public void put(PrmOpportunityAgreementDataImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PrmOpportunityAgreementDataImpl object);

        public abstract void put(PrmOpportunityAgreementDataImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int PRMOPPORTUNITYID = AttributesEnum.PrmOpportunityId.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int TEMPLATEID = AttributesEnum.TemplateId.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int FORM = AttributesEnum.Form.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int EFFECTIVEDATE = AttributesEnum.EffectiveDate.index();
    public static final int TERMLENGTH = AttributesEnum.TermLength.index();
    public static final int CANCELLATIONNOTICETERM = AttributesEnum.CancellationNoticeTerm.index();
    public static final int EXPIRATIONDATE = AttributesEnum.ExpirationDate.index();
    public static final int AUTORENEWTERMMONTHS = AttributesEnum.AutoRenewTermMonths.index();
    public static final int SIGNATORY = AttributesEnum.Signatory.index();
    public static final int CONTRACTSIGNEDDATE = AttributesEnum.ContractSignedDate.index();
    public static final int RIGHTSTOBERETAINED = AttributesEnum.RightsToBeRetained.index();
    public static final int EXCLUSIVITY = AttributesEnum.Exclusivity.index();
    public static final int CONTENTMASTEROWNER = AttributesEnum.ContentMasterOwner.index();
    public static final int TECHNICALCONTACTID = AttributesEnum.TechnicalContactId.index();
    public static final int AGREEMENTCONTACTID = AttributesEnum.AgreementContactId.index();
    public static final int QACONTACTID = AttributesEnum.QaContactId.index();
    public static final int ROYALTYCONTACTID = AttributesEnum.RoyaltyContactId.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int PAYMENTFREQUENCY = AttributesEnum.PaymentFrequency.index();
    public static final int INTERIMPAYMENTTERMDAYS = AttributesEnum.InterimPaymentTermDays.index();
    public static final int ANNUALPAYMENTTERMDAYS = AttributesEnum.AnnualPaymentTermDays.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int AUTORENEWAL = AttributesEnum.AutoRenewal.index();
    public static final int AUTOADD = AttributesEnum.AutoAdd.index();
    public static final int ASSIGNMENT = AttributesEnum.Assignment.index();
    public static final int ROYALTYBEARING = AttributesEnum.RoyaltyBearing.index();
    public static final int GUARANTEE = AttributesEnum.Guarantee.index();
    public static final int FAIRTREATMENTCLAUSE = AttributesEnum.FairTreatmentClause.index();
    public static final int ISSUEEDITIONCOVERAGE = AttributesEnum.IssueEditionCoverage.index();
    public static final int COMPLETECONTENTSET = AttributesEnum.CompleteContentSet.index();
    public static final int WARRANTYANDINDEMNIFICATION = AttributesEnum.WarrantyAndIndemnification.index();
    public static final int GOVERNANCE = AttributesEnum.Governance.index();
    public static final int PRMOPPORTUNITY = AttributesEnum.PrmOpportunity.index();
    public static final int PRMAGREEMNTDATAATTACHMENT = AttributesEnum.PrmAgreemntDataAttachment.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrmOpportunityAgreementDataImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for PrmOpportunityId, using the alias name PrmOpportunityId.
     * @return the PrmOpportunityId
     */
    public Number getPrmOpportunityId() {
        return (Number)getAttributeInternal(PRMOPPORTUNITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrmOpportunityId.
     * @param value value to set the PrmOpportunityId
     */
    public void setPrmOpportunityId(Number value) {
        setAttributeInternal(PRMOPPORTUNITYID, value);
    }

    /**
     * Gets the attribute value for ContractId, using the alias name ContractId.
     * @return the ContractId
     */
    public Number getContractId() {
        return (Number)getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractId.
     * @param value value to set the ContractId
     */
    public void setContractId(Number value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for TemplateId, using the alias name TemplateId.
     * @return the TemplateId
     */
    public Number getTemplateId() {
        return (Number)getAttributeInternal(TEMPLATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TemplateId.
     * @param value value to set the TemplateId
     */
    public void setTemplateId(Number value) {
        setAttributeInternal(TEMPLATEID, value);
    }

    /**
     * Gets the attribute value for Notes, using the alias name Notes.
     * @return the Notes
     */
    public String getNotes() {
        return (String)getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for Notes.
     * @param value value to set the Notes
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * Gets the attribute value for Form, using the alias name Form.
     * @return the Form
     */
    public String getForm() {
        return (String)getAttributeInternal(FORM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Form.
     * @param value value to set the Form
     */
    public void setForm(String value) {
        setAttributeInternal(FORM, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for Type, using the alias name Type.
     * @return the Type
     */
    public String getType() {
        return (String)getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Type.
     * @param value value to set the Type
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for Division, using the alias name Division.
     * @return the Division
     */
    public String getDivision() {
        return (String)getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Division.
     * @param value value to set the Division
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for EffectiveDate, using the alias name EffectiveDate.
     * @return the EffectiveDate
     */
    public Date getEffectiveDate() {
        return (Date)getAttributeInternal(EFFECTIVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveDate.
     * @param value value to set the EffectiveDate
     */
    public void setEffectiveDate(Date value) {
        setAttributeInternal(EFFECTIVEDATE, value);
    }

    /**
     * Gets the attribute value for TermLength, using the alias name TermLength.
     * @return the TermLength
     */
    public String getTermLength() {
        return (String)getAttributeInternal(TERMLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for TermLength.
     * @param value value to set the TermLength
     */
    public void setTermLength(String value) {
        setAttributeInternal(TERMLENGTH, value);
    }

    /**
     * Gets the attribute value for CancellationNoticeTerm, using the alias name CancellationNoticeTerm.
     * @return the CancellationNoticeTerm
     */
    public Number getCancellationNoticeTerm() {
        return (Number)getAttributeInternal(CANCELLATIONNOTICETERM);
    }

    /**
     * Sets <code>value</code> as the attribute value for CancellationNoticeTerm.
     * @param value value to set the CancellationNoticeTerm
     */
    public void setCancellationNoticeTerm(Number value) {
        setAttributeInternal(CANCELLATIONNOTICETERM, value);
    }

    /**
     * Gets the attribute value for ExpirationDate, using the alias name ExpirationDate.
     * @return the ExpirationDate
     */
    public Date getExpirationDate() {
        return (Date)getAttributeInternal(EXPIRATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpirationDate.
     * @param value value to set the ExpirationDate
     */
    public void setExpirationDate(Date value) {
        setAttributeInternal(EXPIRATIONDATE, value);
    }

    /**
     * Gets the attribute value for AutoRenewTermMonths, using the alias name AutoRenewTermMonths.
     * @return the AutoRenewTermMonths
     */
    public Number getAutoRenewTermMonths() {
        return (Number)getAttributeInternal(AUTORENEWTERMMONTHS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AutoRenewTermMonths.
     * @param value value to set the AutoRenewTermMonths
     */
    public void setAutoRenewTermMonths(Number value) {
        setAttributeInternal(AUTORENEWTERMMONTHS, value);
    }

    /**
     * Gets the attribute value for Signatory, using the alias name Signatory.
     * @return the Signatory
     */
    public String getSignatory() {
        return (String)getAttributeInternal(SIGNATORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Signatory.
     * @param value value to set the Signatory
     */
    public void setSignatory(String value) {
        setAttributeInternal(SIGNATORY, value);
    }

    /**
     * Gets the attribute value for ContractSignedDate, using the alias name ContractSignedDate.
     * @return the ContractSignedDate
     */
    public Date getContractSignedDate() {
        return (Date)getAttributeInternal(CONTRACTSIGNEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractSignedDate.
     * @param value value to set the ContractSignedDate
     */
    public void setContractSignedDate(Date value) {
        setAttributeInternal(CONTRACTSIGNEDDATE, value);
    }

    /**
     * Gets the attribute value for RightsToBeRetained, using the alias name RightsToBeRetained.
     * @return the RightsToBeRetained
     */
    public String getRightsToBeRetained() {
        return (String)getAttributeInternal(RIGHTSTOBERETAINED);
    }

    /**
     * Sets <code>value</code> as the attribute value for RightsToBeRetained.
     * @param value value to set the RightsToBeRetained
     */
    public void setRightsToBeRetained(String value) {
        setAttributeInternal(RIGHTSTOBERETAINED, value);
    }

    /**
     * Gets the attribute value for Exclusivity, using the alias name Exclusivity.
     * @return the Exclusivity
     */
    public String getExclusivity() {
        return (String)getAttributeInternal(EXCLUSIVITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Exclusivity.
     * @param value value to set the Exclusivity
     */
    public void setExclusivity(String value) {
        setAttributeInternal(EXCLUSIVITY, value);
    }

    /**
     * Gets the attribute value for ContentMasterOwner, using the alias name ContentMasterOwner.
     * @return the ContentMasterOwner
     */
    public String getContentMasterOwner() {
        return (String)getAttributeInternal(CONTENTMASTEROWNER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContentMasterOwner.
     * @param value value to set the ContentMasterOwner
     */
    public void setContentMasterOwner(String value) {
        setAttributeInternal(CONTENTMASTEROWNER, value);
    }

    /**
     * Gets the attribute value for TechnicalContactId, using the alias name TechnicalContactId.
     * @return the TechnicalContactId
     */
    public Number getTechnicalContactId() {
        return (Number)getAttributeInternal(TECHNICALCONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TechnicalContactId.
     * @param value value to set the TechnicalContactId
     */
    public void setTechnicalContactId(Number value) {
        setAttributeInternal(TECHNICALCONTACTID, value);
    }

    /**
     * Gets the attribute value for AgreementContactId, using the alias name AgreementContactId.
     * @return the AgreementContactId
     */
    public Number getAgreementContactId() {
        return (Number)getAttributeInternal(AGREEMENTCONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AgreementContactId.
     * @param value value to set the AgreementContactId
     */
    public void setAgreementContactId(Number value) {
        setAttributeInternal(AGREEMENTCONTACTID, value);
    }

    /**
     * Gets the attribute value for QaContactId, using the alias name QaContactId.
     * @return the QaContactId
     */
    public Number getQaContactId() {
        return (Number)getAttributeInternal(QACONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for QaContactId.
     * @param value value to set the QaContactId
     */
    public void setQaContactId(Number value) {
        setAttributeInternal(QACONTACTID, value);
    }

    /**
     * Gets the attribute value for RoyaltyContactId, using the alias name RoyaltyContactId.
     * @return the RoyaltyContactId
     */
    public Number getRoyaltyContactId() {
        return (Number)getAttributeInternal(ROYALTYCONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoyaltyContactId.
     * @param value value to set the RoyaltyContactId
     */
    public void setRoyaltyContactId(Number value) {
        setAttributeInternal(ROYALTYCONTACTID, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for PaymentFrequency, using the alias name PaymentFrequency.
     * @return the PaymentFrequency
     */
    public String getPaymentFrequency() {
        return (String)getAttributeInternal(PAYMENTFREQUENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentFrequency.
     * @param value value to set the PaymentFrequency
     */
    public void setPaymentFrequency(String value) {
        setAttributeInternal(PAYMENTFREQUENCY, value);
    }

    /**
     * Gets the attribute value for InterimPaymentTermDays, using the alias name InterimPaymentTermDays.
     * @return the InterimPaymentTermDays
     */
    public Number getInterimPaymentTermDays() {
        return (Number)getAttributeInternal(INTERIMPAYMENTTERMDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for InterimPaymentTermDays.
     * @param value value to set the InterimPaymentTermDays
     */
    public void setInterimPaymentTermDays(Number value) {
        setAttributeInternal(INTERIMPAYMENTTERMDAYS, value);
    }

    /**
     * Gets the attribute value for AnnualPaymentTermDays, using the alias name AnnualPaymentTermDays.
     * @return the AnnualPaymentTermDays
     */
    public Number getAnnualPaymentTermDays() {
        return (Number)getAttributeInternal(ANNUALPAYMENTTERMDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AnnualPaymentTermDays.
     * @param value value to set the AnnualPaymentTermDays
     */
    public void setAnnualPaymentTermDays(Number value) {
        setAttributeInternal(ANNUALPAYMENTTERMDAYS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for AutoRenewal, using the alias name AutoRenewal.
     * @return the AutoRenewal
     */
    public String getAutoRenewal() {
        return (String)getAttributeInternal(AUTORENEWAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for AutoRenewal.
     * @param value value to set the AutoRenewal
     */
    public void setAutoRenewal(String value) {
        setAttributeInternal(AUTORENEWAL, value);
    }

    /**
     * Gets the attribute value for AutoAdd, using the alias name AutoAdd.
     * @return the AutoAdd
     */
    public String getAutoAdd() {
        return (String)getAttributeInternal(AUTOADD);
    }

    /**
     * Sets <code>value</code> as the attribute value for AutoAdd.
     * @param value value to set the AutoAdd
     */
    public void setAutoAdd(String value) {
        setAttributeInternal(AUTOADD, value);
    }

    /**
     * Gets the attribute value for Assignment, using the alias name Assignment.
     * @return the Assignment
     */
    public String getAssignment() {
        return (String)getAttributeInternal(ASSIGNMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Assignment.
     * @param value value to set the Assignment
     */
    public void setAssignment(String value) {
        setAttributeInternal(ASSIGNMENT, value);
    }

    /**
     * Gets the attribute value for RoyaltyBearing, using the alias name RoyaltyBearing.
     * @return the RoyaltyBearing
     */
    public String getRoyaltyBearing() {
        return (String)getAttributeInternal(ROYALTYBEARING);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoyaltyBearing.
     * @param value value to set the RoyaltyBearing
     */
    public void setRoyaltyBearing(String value) {
        setAttributeInternal(ROYALTYBEARING, value);
    }

    /**
     * Gets the attribute value for Guarantee, using the alias name Guarantee.
     * @return the Guarantee
     */
    public String getGuarantee() {
        return (String)getAttributeInternal(GUARANTEE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Guarantee.
     * @param value value to set the Guarantee
     */
    public void setGuarantee(String value) {
        setAttributeInternal(GUARANTEE, value);
    }

    /**
     * Gets the attribute value for FairTreatmentClause, using the alias name FairTreatmentClause.
     * @return the FairTreatmentClause
     */
    public String getFairTreatmentClause() {
        return (String)getAttributeInternal(FAIRTREATMENTCLAUSE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FairTreatmentClause.
     * @param value value to set the FairTreatmentClause
     */
    public void setFairTreatmentClause(String value) {
        setAttributeInternal(FAIRTREATMENTCLAUSE, value);
    }

    /**
     * Gets the attribute value for IssueEditionCoverage, using the alias name IssueEditionCoverage.
     * @return the IssueEditionCoverage
     */
    public String getIssueEditionCoverage() {
        return (String)getAttributeInternal(ISSUEEDITIONCOVERAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IssueEditionCoverage.
     * @param value value to set the IssueEditionCoverage
     */
    public void setIssueEditionCoverage(String value) {
        setAttributeInternal(ISSUEEDITIONCOVERAGE, value);
    }

    /**
     * Gets the attribute value for CompleteContentSet, using the alias name CompleteContentSet.
     * @return the CompleteContentSet
     */
    public String getCompleteContentSet() {
        return (String)getAttributeInternal(COMPLETECONTENTSET);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompleteContentSet.
     * @param value value to set the CompleteContentSet
     */
    public void setCompleteContentSet(String value) {
        setAttributeInternal(COMPLETECONTENTSET, value);
    }

    /**
     * Gets the attribute value for WarrantyAndIndemnification, using the alias name WarrantyAndIndemnification.
     * @return the WarrantyAndIndemnification
     */
    public String getWarrantyAndIndemnification() {
        return (String)getAttributeInternal(WARRANTYANDINDEMNIFICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarrantyAndIndemnification.
     * @param value value to set the WarrantyAndIndemnification
     */
    public void setWarrantyAndIndemnification(String value) {
        setAttributeInternal(WARRANTYANDINDEMNIFICATION, value);
    }

    /**
     * Gets the attribute value for Governance, using the alias name Governance.
     * @return the Governance
     */
    public String getGovernance() {
        return (String)getAttributeInternal(GOVERNANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Governance.
     * @param value value to set the Governance
     */
    public void setGovernance(String value) {
        setAttributeInternal(GOVERNANCE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity PrmOpportunityImpl.
     */
    public PrmOpportunityImpl getPrmOpportunity() {
        return (PrmOpportunityImpl)getAttributeInternal(PRMOPPORTUNITY);
    }

    /**
     * Sets <code>value</code> as the associated entity PrmOpportunityImpl.
     */
    public void setPrmOpportunity(PrmOpportunityImpl value) {
        setAttributeInternal(PRMOPPORTUNITY, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPrmAgreemntDataAttachment() {
        return (RowIterator)getAttributeInternal(PRMAGREEMNTDATAATTACHMENT);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.pq.tracs.model.eo.PrmOpportunityAgreementData");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
       
        this.setCompleteContentSet("Yes");
        this.setRoyaltyBearing("Yes");
        this.setFairTreatmentClause("Yes");
        this.setIssueEditionCoverage("Yes");
        this.setAssignment("Standard");
        this.setGovernance("Michigan");
        this.setWarrantyAndIndemnification("Standard");
    }
}
