package com.pq.tracs.model.eo;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 16 07:09:25 EDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TraxVaryingFormImpl extends PrmBaseEntity {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getId();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        TitleId {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getTitleId();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setTitleId((Number)value);
            }
        }
        ,
        TitleRecordId {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getTitleRecordId();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setTitleRecordId((Number)value);
            }
        }
        ,
        PrimaryFlag {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getPrimaryFlag();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setPrimaryFlag((String)value);
            }
        }
        ,
        VaryingForm {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getVaryingForm();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setVaryingForm((String)value);
            }
        }
        ,
        TypeOfTitle {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getTypeOfTitle();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setTypeOfTitle((String)value);
            }
        }
        ,
        PrintFlag {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getPrintFlag();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setPrintFlag((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedDate {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TraxTitle1 {
            public Object get(TraxVaryingFormImpl obj) {
                return obj.getTraxTitle1();
            }

            public void put(TraxVaryingFormImpl obj, Object value) {
                obj.setTraxTitle1((TraxTitleImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TraxVaryingFormImpl object);

        public abstract void put(TraxVaryingFormImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ID = AttributesEnum.Id.index();
    public static final int TITLEID = AttributesEnum.TitleId.index();
    public static final int TITLERECORDID = AttributesEnum.TitleRecordId.index();
    public static final int PRIMARYFLAG = AttributesEnum.PrimaryFlag.index();
    public static final int VARYINGFORM = AttributesEnum.VaryingForm.index();
    public static final int TYPEOFTITLE = AttributesEnum.TypeOfTitle.index();
    public static final int PRINTFLAG = AttributesEnum.PrintFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int TRAXTITLE1 = AttributesEnum.TraxTitle1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TraxVaryingFormImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.pq.tracs.model.eo.TraxVaryingForm");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for TitleId, using the alias name TitleId.
     * @return the TitleId
     */
    public Number getTitleId() {
        return (Number)getAttributeInternal(TITLEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TitleId.
     * @param value value to set the TitleId
     */
    public void setTitleId(Number value) {
        setAttributeInternal(TITLEID, value);
    }

    /**
     * Gets the attribute value for TitleRecordId, using the alias name TitleRecordId.
     * @return the TitleRecordId
     */
    public Number getTitleRecordId() {
        return (Number)getAttributeInternal(TITLERECORDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TitleRecordId.
     * @param value value to set the TitleRecordId
     */
    public void setTitleRecordId(Number value) {
        setAttributeInternal(TITLERECORDID, value);
    }

    /**
     * Gets the attribute value for PrimaryFlag, using the alias name PrimaryFlag.
     * @return the PrimaryFlag
     */
    public String getPrimaryFlag() {
        return (String)getAttributeInternal(PRIMARYFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrimaryFlag.
     * @param value value to set the PrimaryFlag
     */
    public void setPrimaryFlag(String value) {
        setAttributeInternal(PRIMARYFLAG, value);
    }

    /**
     * Gets the attribute value for VaryingForm, using the alias name VaryingForm.
     * @return the VaryingForm
     */
    public String getVaryingForm() {
        return (String)getAttributeInternal(VARYINGFORM);
    }

    /**
     * Sets <code>value</code> as the attribute value for VaryingForm.
     * @param value value to set the VaryingForm
     */
    public void setVaryingForm(String value) {
        setAttributeInternal(VARYINGFORM, value);
    }

    /**
     * Gets the attribute value for TypeOfTitle, using the alias name TypeOfTitle.
     * @return the TypeOfTitle
     */
    public String getTypeOfTitle() {
        return (String)getAttributeInternal(TYPEOFTITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TypeOfTitle.
     * @param value value to set the TypeOfTitle
     */
    public void setTypeOfTitle(String value) {
        setAttributeInternal(TYPEOFTITLE, value);
    }

    /**
     * Gets the attribute value for PrintFlag, using the alias name PrintFlag.
     * @return the PrintFlag
     */
    public String getPrintFlag() {
        return (String)getAttributeInternal(PRINTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrintFlag.
     * @param value value to set the PrintFlag
     */
    public void setPrintFlag(String value) {
        setAttributeInternal(PRINTFLAG, value);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity TraxTitleImpl.
     */
    public TraxTitleImpl getTraxTitle1() {
        return (TraxTitleImpl)getAttributeInternal(TRAXTITLE1);
    }

    /**
     * Sets <code>value</code> as the associated entity TraxTitleImpl.
     */
    public void setTraxTitle1(TraxTitleImpl value) {
        setAttributeInternal(TRAXTITLE1, value);
    }


    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }

    protected void validateEntity() {
        super.validateEntity();
        
        if (this.getTraxTitle1() != null && this.getPrimaryFlag().equalsIgnoreCase("Y")) {
            // if primary flag is set on this record, then mark the title as invalid so it will validat the primary flags
            this.getTraxTitle1().setInvalid();
        }
    }

}
