package com.pq.tracs.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 10 11:02:38 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TraxAddressImpl extends PrmBaseEntity {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(TraxAddressImpl obj) {
                return obj.getId();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        ContentOwnerId {
            public Object get(TraxAddressImpl obj) {
                return obj.getContentOwnerId();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setContentOwnerId((Number)value);
            }
        }
        ,
        PrimaryFlag {
            public Object get(TraxAddressImpl obj) {
                return obj.getPrimaryFlag();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setPrimaryFlag((String)value);
            }
        }
        ,
        BillToFlag {
            public Object get(TraxAddressImpl obj) {
                return obj.getBillToFlag();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setBillToFlag((String)value);
            }
        }
        ,
        ShipToFlag {
            public Object get(TraxAddressImpl obj) {
                return obj.getShipToFlag();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setShipToFlag((String)value);
            }
        }
        ,
        ActiveFlag {
            public Object get(TraxAddressImpl obj) {
                return obj.getActiveFlag();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setActiveFlag((String)value);
            }
        }
        ,
        SiteOrDepartment {
            public Object get(TraxAddressImpl obj) {
                return obj.getSiteOrDepartment();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setSiteOrDepartment((String)value);
            }
        }
        ,
        AddressLine1 {
            public Object get(TraxAddressImpl obj) {
                return obj.getAddressLine1();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setAddressLine1((String)value);
            }
        }
        ,
        AddressLine2 {
            public Object get(TraxAddressImpl obj) {
                return obj.getAddressLine2();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setAddressLine2((String)value);
            }
        }
        ,
        City {
            public Object get(TraxAddressImpl obj) {
                return obj.getCity();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setCity((String)value);
            }
        }
        ,
        StateOrProvince {
            public Object get(TraxAddressImpl obj) {
                return obj.getStateOrProvince();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setStateOrProvince((String)value);
            }
        }
        ,
        ZipOrPostalCode {
            public Object get(TraxAddressImpl obj) {
                return obj.getZipOrPostalCode();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setZipOrPostalCode((String)value);
            }
        }
        ,
        Country {
            public Object get(TraxAddressImpl obj) {
                return obj.getCountry();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        County {
            public Object get(TraxAddressImpl obj) {
                return obj.getCounty();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setCounty((String)value);
            }
        }
        ,
        SitePhoneNumber {
            public Object get(TraxAddressImpl obj) {
                return obj.getSitePhoneNumber();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setSitePhoneNumber((String)value);
            }
        }
        ,
        EffectiveStartDate {
            public Object get(TraxAddressImpl obj) {
                return obj.getEffectiveStartDate();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setEffectiveStartDate((Date)value);
            }
        }
        ,
        AddressComments {
            public Object get(TraxAddressImpl obj) {
                return obj.getAddressComments();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setAddressComments((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(TraxAddressImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedDate {
            public Object get(TraxAddressImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(TraxAddressImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(TraxAddressImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TraxContentOwner {
            public Object get(TraxAddressImpl obj) {
                return obj.getTraxContentOwner();
            }

            public void put(TraxAddressImpl obj, Object value) {
                obj.setTraxContentOwner((TraxContentOwnerImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TraxAddressImpl object);

        public abstract void put(TraxAddressImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int CONTENTOWNERID = AttributesEnum.ContentOwnerId.index();
    public static final int PRIMARYFLAG = AttributesEnum.PrimaryFlag.index();
    public static final int BILLTOFLAG = AttributesEnum.BillToFlag.index();
    public static final int SHIPTOFLAG = AttributesEnum.ShipToFlag.index();
    public static final int ACTIVEFLAG = AttributesEnum.ActiveFlag.index();
    public static final int SITEORDEPARTMENT = AttributesEnum.SiteOrDepartment.index();
    public static final int ADDRESSLINE1 = AttributesEnum.AddressLine1.index();
    public static final int ADDRESSLINE2 = AttributesEnum.AddressLine2.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int STATEORPROVINCE = AttributesEnum.StateOrProvince.index();
    public static final int ZIPORPOSTALCODE = AttributesEnum.ZipOrPostalCode.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int COUNTY = AttributesEnum.County.index();
    public static final int SITEPHONENUMBER = AttributesEnum.SitePhoneNumber.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int ADDRESSCOMMENTS = AttributesEnum.AddressComments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int TRAXCONTENTOWNER = AttributesEnum.TraxContentOwner.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TraxAddressImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for ContentOwnerId, using the alias name ContentOwnerId.
     * @return the ContentOwnerId
     */
    public Number getContentOwnerId() {
        return (Number)getAttributeInternal(CONTENTOWNERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContentOwnerId.
     * @param value value to set the ContentOwnerId
     */
    public void setContentOwnerId(Number value) {
        setAttributeInternal(CONTENTOWNERID, value);
    }

    /**
     * Gets the attribute value for PrimaryFlag, using the alias name PrimaryFlag.
     * @return the PrimaryFlag
     */
    public String getPrimaryFlag() {
        return (String)getAttributeInternal(PRIMARYFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrimaryFlag.
     * @param value value to set the PrimaryFlag
     */
    public void setPrimaryFlag(String value) {
        setAttributeInternal(PRIMARYFLAG, value);
    }

    /**
     * Gets the attribute value for BillToFlag, using the alias name BillToFlag.
     * @return the BillToFlag
     */
    public String getBillToFlag() {
        return (String)getAttributeInternal(BILLTOFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillToFlag.
     * @param value value to set the BillToFlag
     */
    public void setBillToFlag(String value) {
        setAttributeInternal(BILLTOFLAG, value);
    }

    /**
     * Gets the attribute value for ShipToFlag, using the alias name ShipToFlag.
     * @return the ShipToFlag
     */
    public String getShipToFlag() {
        return (String)getAttributeInternal(SHIPTOFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipToFlag.
     * @param value value to set the ShipToFlag
     */
    public void setShipToFlag(String value) {
        setAttributeInternal(SHIPTOFLAG, value);
    }

    /**
     * Gets the attribute value for ActiveFlag, using the alias name ActiveFlag.
     * @return the ActiveFlag
     */
    public String getActiveFlag() {
        return (String)getAttributeInternal(ACTIVEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActiveFlag.
     * @param value value to set the ActiveFlag
     */
    public void setActiveFlag(String value) {
        setAttributeInternal(ACTIVEFLAG, value);
    }

    /**
     * Gets the attribute value for SiteOrDepartment, using the alias name SiteOrDepartment.
     * @return the SiteOrDepartment
     */
    public String getSiteOrDepartment() {
        return (String)getAttributeInternal(SITEORDEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SiteOrDepartment.
     * @param value value to set the SiteOrDepartment
     */
    public void setSiteOrDepartment(String value) {
        setAttributeInternal(SITEORDEPARTMENT, value);
    }

    /**
     * Gets the attribute value for AddressLine1, using the alias name AddressLine1.
     * @return the AddressLine1
     */
    public String getAddressLine1() {
        return (String)getAttributeInternal(ADDRESSLINE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddressLine1.
     * @param value value to set the AddressLine1
     */
    public void setAddressLine1(String value) {
        setAttributeInternal(ADDRESSLINE1, value);
    }

    /**
     * Gets the attribute value for AddressLine2, using the alias name AddressLine2.
     * @return the AddressLine2
     */
    public String getAddressLine2() {
        return (String)getAttributeInternal(ADDRESSLINE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddressLine2.
     * @param value value to set the AddressLine2
     */
    public void setAddressLine2(String value) {
        setAttributeInternal(ADDRESSLINE2, value);
    }

    /**
     * Gets the attribute value for City, using the alias name City.
     * @return the City
     */
    public String getCity() {
        return (String)getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for City.
     * @param value value to set the City
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for StateOrProvince, using the alias name StateOrProvince.
     * @return the StateOrProvince
     */
    public String getStateOrProvince() {
        return (String)getAttributeInternal(STATEORPROVINCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StateOrProvince.
     * @param value value to set the StateOrProvince
     */
    public void setStateOrProvince(String value) {
        setAttributeInternal(STATEORPROVINCE, value);
    }

    /**
     * Gets the attribute value for ZipOrPostalCode, using the alias name ZipOrPostalCode.
     * @return the ZipOrPostalCode
     */
    public String getZipOrPostalCode() {
        return (String)getAttributeInternal(ZIPORPOSTALCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ZipOrPostalCode.
     * @param value value to set the ZipOrPostalCode
     */
    public void setZipOrPostalCode(String value) {
        setAttributeInternal(ZIPORPOSTALCODE, value);
    }

    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the Country
     */
    public String getCountry() {
        return (String)getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for County, using the alias name County.
     * @return the County
     */
    public String getCounty() {
        return (String)getAttributeInternal(COUNTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for County.
     * @param value value to set the County
     */
    public void setCounty(String value) {
        setAttributeInternal(COUNTY, value);
    }

    /**
     * Gets the attribute value for SitePhoneNumber, using the alias name SitePhoneNumber.
     * @return the SitePhoneNumber
     */
    public String getSitePhoneNumber() {
        return (String)getAttributeInternal(SITEPHONENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SitePhoneNumber.
     * @param value value to set the SitePhoneNumber
     */
    public void setSitePhoneNumber(String value) {
        setAttributeInternal(SITEPHONENUMBER, value);
    }

    /**
     * Gets the attribute value for EffectiveStartDate, using the alias name EffectiveStartDate.
     * @return the EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date)getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveStartDate.
     * @param value value to set the EffectiveStartDate
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for AddressComments, using the alias name AddressComments.
     * @return the AddressComments
     */
    public String getAddressComments() {
        return (String)getAttributeInternal(ADDRESSCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddressComments.
     * @param value value to set the AddressComments
     */
    public void setAddressComments(String value) {
        setAttributeInternal(ADDRESSCOMMENTS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity TraxContentOwnerImpl.
     */
    public TraxContentOwnerImpl getTraxContentOwner() {
        return (TraxContentOwnerImpl)getAttributeInternal(TRAXCONTENTOWNER);
    }

    /**
     * Sets <code>value</code> as the associated entity TraxContentOwnerImpl.
     */
    public void setTraxContentOwner(TraxContentOwnerImpl value) {
        setAttributeInternal(TRAXCONTENTOWNER, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.pq.tracs.model.eo.TraxAddress");
        }
        return mDefinitionObject;
    }


    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
  

    @Override
    protected void prepareForDML(int operation, TransactionEvent e) {
      super.prepareForDML(operation, e);
        
         try {
             if (getContentOwnerId()!=null &&(operation == DML_INSERT || operation == DML_UPDATE)) {
                 if(this.getTraxContentOwner().getTraxAddress().getRowCount()<=1){
                     setPrimaryFlag("Y");
                 }
             }
         } catch (Exception efg) {
             
         }       
        
    }

    protected void validateEntity() {
        super.validateEntity();
         
        if(("United States".equals(getCountry()) || "Canada".equals(getCountry())) && (getStateOrProvince()==null || getStateOrProvince().trim().length()==0)){
            throw new JboException("State Or Province - Required value for United States and Canada.");
        }

        if (this.getPrimaryFlag().equalsIgnoreCase("Y")) {
            // if primary flag is set on this record, then mark the title as invalid so it will validat the primary flags
            this.getTraxContentOwner().setInvalid();
        }
    }

}
