package com.pq.tracs.model.vo;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 31 16:57:07 EDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TraxImportFileViewImpl extends PRMView {
    /**
     * This is the default constructor (do not remove).
     */
    public TraxImportFileViewImpl() {
    }
}
